# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a77bf3b0359d0aafdd87a40202385174"
name = "Test Custom Bundles"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_cart_transforms,write_products,write_discounts"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
