api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "bundles-cart-lines-merge"
type = "function"
uid = "1c9b6f63-73df-ffcd-dad3-0fbd7151f63abd97fea8"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
