api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "custom-bundles"
type = "function"
uid = "e4384226-4d78-abbc-9b46-34e3198d0248f254a560"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
